name: pytest-uv

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13", "3.13t"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run pytest (minimal)
        run: uv run pytest
